### ISSUE TITLE
Adicionar a pasta /node_modules no .gitignore!

### ISSUE THREAD

**Issue by kelvne** [viniciusrc15/ProjetoFormulario#1]
Tudo bom, gente? 

Não esqueçam de criar um arquivo `.gitignore` para remover arquivos desnecessários do repositório, como a pasta `/node_modules`! 😄

**Comment by viniciusrc15** [comment]
Opa, obrigado pela dica irei fazer!!

**Comment by peidrao** [comment]
Infelizmente não consigo incluir essa pasta. Já tentei "node_modules", "/node_modules" e "./node_modules" e mesmo assim a pasta não é incluída no .gitignore

**Comment by AndersonLima12** [comment]
@peidrao E ai mano, tenta criar o arquivo .gitignore e dentro dele você joga essa estrutura de comandos ai...

# dependencies
/node_modules
/.pnp
.pnp.js

# testing
/coverage

# production
/build

# misc
.DS_Store
.env.local
.env.development.local
.env.test.local
.env.production.local

npm-debug.log*
yarn-debug.log*
yarn-error.log*
